name: responsive_builder
description: A responsive builder for your projects in specially designed to be closest on web way, defining the breakpoints
version: 0.0.1
author: Helio S. Junior <hj_junior@hotmail.com>
homepage: hjjunior.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
